// <auto-generated />
namespace NewsSystem.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_dataannotation_to_MediaLibrary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_dataannotation_to_MediaLibrary));
        
        string IMigrationMetadata.Id
        {
            get { return "201806260639086_add_dataannotation_to_MediaLibrary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
